# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c4da4a9bac6aa644a3f4644330eab40bd7d802614ec3616b89f5f655332a0a0e0d7ab4a4c05b3c7827fbbe8ed24c36e4f443df2f0de2cec9a2033e81b4aaf4

test:
  secret_key_base: 51d4aae4f92f4d397d8d4d75957467911ff02862ec406cee68e9caabae68249b71b84f5d80d0c33aca4a124caa8906d7a68d2cb2cbce292aa78a83bcdf586d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
